LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := bt_lnp_fw
LOCAL_MODULE_OWNER := intel
LOCAL_MODULE_TAGS := optional
LOCAL_REQUIRED_MODULES := \
        370b12060002340e00.sfi \
        370b10060002220e00.sfi \
        370b000600020d0e00.sfi \
        370b00060002280d00.seq \
        370b12060002340e00_selftest.sfi \
        370b10060002220e00_selftest.sfi \
        bddata_B2_C0 \
        bddata_B0 \
        bddata_K0 \
        bddata_A0 \
include $(BUILD_PHONY_PACKAGE)

#################################################
#LnP: B2/C0
include $(CLEAR_VARS)
LOCAL_MODULE := 370b12060002340e00.sfi
LOCAL_MODULE_OWNER := intel
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/bt
LOCAL_SRC_FILES := 370b12060002340e00.sfi
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := bddata_B2_C0
LOCAL_MODULE_OWNER := intel
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/bluetooth
LOCAL_SRC_FILES := bddata_B2_C0
include $(BUILD_PREBUILT)

#LnP: B0
include $(CLEAR_VARS)
LOCAL_MODULE := 370b10060002220e00.sfi
LOCAL_MODULE_OWNER := intel
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/bt
LOCAL_SRC_FILES := 370b10060002220e00.sfi
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := bddata_B0
LOCAL_MODULE_OWNER := intel
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/bluetooth
LOCAL_SRC_FILES := bddata_B0
include $(BUILD_PREBUILT)

#LnP: K0
include $(CLEAR_VARS)
LOCAL_MODULE := 370b000600020d0e00.sfi
LOCAL_MODULE_OWNER := intel
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/bt
LOCAL_SRC_FILES := 370b000600020d0e00.sfi
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := bddata_K0
LOCAL_MODULE_OWNER := intel
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/bluetooth
LOCAL_SRC_FILES := bddata_K0
include $(BUILD_PREBUILT)

#LnP: A0-A3
include $(CLEAR_VARS)
LOCAL_MODULE := 370b00060002280d00.seq
LOCAL_MODULE_OWNER := intel
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/bt
LOCAL_SRC_FILES := 370b00060002280d00.seq
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := bddata_A0
LOCAL_MODULE_OWNER := intel
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/bluetooth
LOCAL_SRC_FILES := bddata_A0
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := bddata
LOCAL_MODULE_OWNER := intel
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/bluetooth
LOCAL_SRC_FILES := bddata
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := nvm_init.sh
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT)/etc/bluetooth
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := a00.pbn
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT)/etc/bluetooth
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := a10.pbn
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT)/etc/bluetooth
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := a11.pbn
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT)/etc/bluetooth
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

# LnP: Self-Test: B2/C0
include $(CLEAR_VARS)
LOCAL_MODULE := 370b12060002340e00_selftest.sfi
LOCAL_MODULE_OWNER := intel
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/bt
LOCAL_SRC_FILES := 370b12060002340e00_selftest.sfi
include $(BUILD_PREBUILT)

# LnP: Self-Test: B0
include $(CLEAR_VARS)
LOCAL_MODULE := 370b10060002220e00_selftest.sfi
LOCAL_MODULE_OWNER := intel
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_ETC)/firmware/bt
LOCAL_SRC_FILES := 370b10060002220e00_selftest.sfi
include $(BUILD_PREBUILT)
